# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       kf5-kconfig

# >> macros
# << macros

Summary:    KDE Frameworks 5 Tier 1 addon with advanced configuration system
Version:    4.99.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kf5-kconfig.yaml
Requires:   kf5-filesystem
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
Provides:   kf5-kconfig-core%{?_isa} = %{version}-%{release}
Provides:   kf5-kconfig-gui%{?_isa} = %{version}-%{release}

%description
KDE Frameworks 5 Tier 1 addon with advanced configuration system made of two parts:
KConfigCore and KConfigGui.


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
The %{name}-devel package contains the files necessary to develop applications |
that use %{name}.


%package core
Summary:    Non-GUI part of KConfig framework
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description core
KConfigCore provides access to the configuration files themselves. It features:

- centralized definition: define your configuration in an XML file and use
`kconfig_compiler` to generate classes to read and write configuration entries.

- lock-down (kiosk) support.


%package gui
Summary:    GUI part of KConfig framework
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   kf5-kconfig-core%{?_isa} = %{version}-%{release}

%description gui
KConfigGui provides a way to hook widgets to the configuration so that they are
automatically initialized from the configuration and automatically propagate
their changes to their respective configuration files.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kf5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kf5_make_install
%find_lang kconfig5_qt --with-qt --all-name || :
# << install pre

# >> install post
# << install post

%files -f kconfig5_qt.lang
%defattr(-,root,root,-)
%{_kf5_bindir}/kreadconfig5
%{_kf5_bindir}/kwriteconfig5
%{_kf5_bindir}/kconfig_compiler_kf5
%{_kf5_libdir}/libKF5ConfigCore.so.*
%{_kf5_libexecdir}/kconf_update
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_kf5_includedir}/kconfig_version.h
%{_kf5_includedir}/KConfigCore
%{_kf5_includedir}/KConfigGui
%{_kf5_libdir}/libKF5ConfigCore.so
%{_kf5_libdir}/libKF5ConfigGui.so
%{_kf5_libdir}/cmake/KF5Config
%{_kf5_archdatadir}/mkspecs/modules/qt_KConfigCore.pri
%{_kf5_archdatadir}/mkspecs/modules/qt_KConfigGui.pri
# >> files devel
# << files devel

%files core
%defattr(-,root,root,-)
%{_kf5_includedir}/kconfig_version.h
%{_kf5_includedir}/KConfigCore
%{_kf5_includedir}/KConfigGui
%{_kf5_libdir}/libKF5ConfigCore.so
%{_kf5_libdir}/libKF5ConfigGui.so
%{_kf5_libdir}/cmake/KF5Config
%{_kf5_archdatadir}/mkspecs/modules/qt_KConfigCore.pri
%{_kf5_archdatadir}/mkspecs/modules/qt_KConfigGui.pri
# >> files core
# << files core

%files gui
%defattr(-,root,root,-)
%{_kf5_libdir}/libKF5ConfigGui.so.*
# >> files gui
# << files gui
